import React from "react";
import Head from "next/head";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import StarButton from "../../components/StarButton";
import { getAllPostsForHome } from "../../lib/api";
import { Card } from "../../components/Card";
import Link from "next/link";
import clsx from "clsx";

type Props = {
  allPosts: any;
};

const consultation_individuel = ({ allPosts }: Props) => {
  return (
    <>
      <Head>
        <title>Selene-Yoga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-xs md:text-base font-main">
        <Navbar />

        <div className="relative h-32">
          <div className="absolute inset-0 flex flex-col justify-center center-content items-center z-10">
            <div>
              <div className="text-center text-selene-green-dark bold text-4xl font-serif">
                Articles
              </div>
            </div>
          </div>
        </div>
        <div className="flex justify-left">
          <Link href="/">
            <StarButton title="Accueil" className="px-10 py-3 m-3" />
          </Link>
        </div>
        <div
          className={clsx(
            "grid grid-cols-1 gap-1 m-10 justify-items-center justify-content-center ",
            "sm:grid-cols-2 sm:gap-2",
            "md:grid-cols-3 md:gap-3",
            "lg:grid-cols-4 lg:gap-4"
          )}
        >
          {allPosts.map((post: any) => (
            <Card
              key={post.slug}
              img={post.coverImage.url}
              title={post.title}
              subTitle={post.excerpt}
              link={post.slug}
              id={post.id}
            />
          ))}
        </div>
        <Footer bgClassName="bg-gradient-to-t from-selene-green to-selene-green-dark" />
      </main>
    </>
  );
};

export default consultation_individuel;

export async function getStaticProps({ preview = false }) {
  const allPosts = (await getAllPostsForHome(preview)) ?? [];
  return {
    props: { preview, allPosts },
  };
}
