import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'

import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import Intro from '../components/Intro'
import Section from '../components/Section'
import Actu from '../components/Actu'
import News from '../components/News'
import Contact from '../components/Contact'
import Soins from '../components/Soins'
import Practices from '../components/Practices'
import Modal from '../components/Modal'

export default function Home() {
  return (
    < >
      <Head>
        <title>Selene-Yoga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='text-xs md:text-base font-main'>
        <Navbar/>
        <Modal/>
        <Intro/>
        <Section title='Actualités - évènements'>
          <Actu/>
        </Section>
        <Section title='Articles'>
          <News/>
        </Section>
        <Section title='Les soins'>
          <Soins/>
        </Section>
        <Section title='Les pratiques'>
          <Practices/>
        </Section>
        <Section title='Contact'>
          <Contact/>
        </Section>
        <Footer/>
      </main>
    </>
  )
}
