import Head from 'next/head'
import Image from 'next/image'
import {useState} from 'react'

import sunshide_mountain from '../Images/z-s-nqVDLh2WLus-unsplash_1.jpg'
import moutain_lake from '../Images/mountain_lake.png'
import flo_shadow from '../Images/flo_shadow.jpg'

import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import Intro from '../components/Intro'
import Section from '../components/Section'
import Actu from '../components/Actu'
import News from '../components/News'
import Contact from '../components/Contact'
import Soins from '../components/Soins'
import Practices from '../components/Practices'
import Modal from '../components/Modal'
import Story from '../components/Story'



export default function Home() {
  const [story, setStory] = useState<boolean>(false)
  return (
    < >
      <Head>
        <title>Selene-Yoga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='text-xs md:text-base font-main'>
        <Navbar/>
        <Modal/>
        <Section name='intro' bgImg={moutain_lake}>
          <Intro/>
        </Section>
        <Section title='Actualités - évènements' name='events' color='selene-green'>
          <Actu/>
        </Section>
        <Section title='Articles' color='selene-green' name='news' bg="gradient-to-b from-white to-selene-white">
          <News/>
        </Section>
        <Section title='Les soins'  color='selene-green' name='soins' bgImg={sunshide_mountain}>
          <Soins/>
        </Section>
        <Section title='Les pratiques'  color='white' name='practices' bg="gradient-to-b from-selene-green-dark to-selene-green">
          <Practices/>
        </Section>
        <Section title='Contact' color='white' name='contact' bgImg={flo_shadow}>
          <Contact handleStory={story} setHandleStory={setStory}/>
        </Section>
        {story && (<Section color='white' name='story'>
          <Story/>
        </Section>)}
        <Footer/>
      </main>
    </>
  )
}
