import React from 'react'
import Navbar from '../components/Navbar'
import Head from 'next/head'
import Footer from '../components/Footer'
import img from '../Images/mountain_sky_star.jpg'
import Image from 'next/image'

type Props = {}

const Oeuvre = (props: Props) => {
  return (
    <>
    <Head>
        <title>Selene-Yoga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='text-xs md:text-base font-main'>
        <Navbar/>
        <div  className="relative h-32 overflow-hidden">
          <div className='flex flex-col justify-center center-content h-full'>
            <div>
              <div className=' relative z-[1] text-center text-white bold text-4xl font-serif'>Consultations <br/>Individuelles</div>
            </div>
          </div>
        <Image src={img} alt={'moutain sky star'} fill  placeholder='blur'/>
        </div>
        <p className='p-10 text-center'>
          L’intention :
          <br />
          Mon entreprise se nomme Séléné Yoga
          Sa vocation est inscrite en son nom : proposer d’entrer en union avec la vie par la reconnaissance et 
          l’acceptation de notre part sensible, profonde, mystérieuse.
          <br />
          <br />
          Se rencontrer dans sa vérité, au-delà des masques que l’on porte, c’est non seulement retrouver l’énergie, 
          mais également l’enthousiasme d’avancer avec son cœur ; c’est passer du labeur du quotidien qui nous pèse, 
          à nous offrir à la vie avec légèreté, et naître à soi-même à chaque instant, sur ce chemin.
          <br />
          <br />
          Pour révéler mon potentiel, il m’a été utile d’utiliser des symboles et des systèmes de compréhensions 
          (yi king, tarot, astrologie, human design) qui ne restent que des marches pour se connaître à travers des images.
          <br />
          <br />
          Il m’a été utile de cultiver cette énergie, goûter a son élévation et à son tarissement, apprendre à se connecter 
          à cet espace qui ressource et sécurise, et voir la danse de cette énergie opérer dans la vie courante.
          <br />
          <br />
          Ces deux pratiques de connaissance de soi, par le symbole et par l’élévation de son énergie sont deux voies qui nous 
          mènent à révéler la nature non duelle du monde, et ainsi s’ancrer dans cette vie ou l’autre est un autre soi, ou notre 
          propre soi.
          <br />
          <br />
          Connaître la joie de n’être personne, s’oublier dans la mouvance de la vie… C’est épouser la danse de notre étoile et 
          invité son rayonnement sur terre.
        </p>
        


        <Footer bgClassName='bg-gradient-to-t from-selene-green to-selene-green-dark'/>
      </main>
    </>
  )
}

export default Oeuvre