import React from 'react'
import Head from 'next/head'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import StarButton from '../components/StarButton'
import Image from 'next/image'
import img2 from '../Images/mountain_sunset.jpg'

type Props = {}

const Rencontres = (props: Props) => {
  return (
    <>
    <Head>
        <title>Selene-Yoga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='text-xs md:text-base font-main'>
        <Navbar/>
        <div  className="relative h-32 overflow-hidden">
          <div className='flex flex-col justify-center center-content h-full'>
            <div>
              <div className=' relative z-[1] text-center text-white bold text-4xl font-serif'>Rencontres collectives</div>
            </div>
          </div>
        <Image src={img2} alt={'Mountain sunset'}
        fill
        placeholder='blur'/>
        </div>
        <p className='p-10 text-center'>
          Que cela soit à travers des ateliers, des séminaires ou des stages, 
          j’ai plaisir à animer ces évènements dans une dimension de partage, d’ouverture, 
          d’offrir une attention particulière au rythme qui nous emporte, et retrouver notre propre mouvement, dynamique et regard.
          <br />
          <br />
          Des ateliers proposeront d’explorer en groupe des thématiques telles que la nature et sa nature, notre relation 
          a nous-même et au monde, la danse des saisons et la reliance à l’énergie… Afin d’apprendre ensemble à réenchanter 
          notre monde.
          <br />
          <br />
          Ces ateliers ou stage sur week-end proposeront un programme équilibré entre l’activité, l’étude et le repos, 
          ponctué de pratiques de bien-être. Ils sont des espaces offerts à la connaissance de Soi, dans le partage, 
          la bienveillance et le respect.
        </p>
        <div className='flex justify-center'>
          <StarButton title='Me contacter' className='px-10 py-3 m-3'/>
        </div>

        <Footer bgClassName='bg-gradient-to-t from-selene-green to-selene-green-dark'/>
      </main>
    </>
  )
}

export default Rencontres